openapi: 3.0.0
info:
  title: RAG-Based Interactive Book Chatbot - Selection Ask API
  description: API for asking questions about specific selected text
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /ask-selection:
    post:
      summary: Ask a question about specific selected text
      description: Submit a question to be answered based on specific selected text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The question to ask about the selected text
                  example: "Can you explain this concept in more detail?"
                selected_text:
                  type: string
                  description: The text that was selected by the user
                  example: "The main concept here is that..."
                  maxLength: 5000
                session_id:
                  type: string
                  description: The user's session identifier
                  example: "sess_1234567890"
              required:
                - question
                - selected_text
                - session_id
      responses:
        '200':
          description: Successful response with answer and sources
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The answer to the question
                    example: "The concept refers to..."
                  sources:
                    type: array
                    items:
                      type: string
                    description: List of source references used to generate the answer
                    example: ["Selected text", "Chapter 2"]
                  session_id:
                    type: string
                    description: The session identifier
        '400':
          description: Bad request - invalid input or text too long
        '500':
          description: Internal server error
      tags:
        - Ask-Selection